# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-04 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170304_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='Image',
            new_name='image',
        ),
    ]
