# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170306_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u5206\u949f\u6570\uff09'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visit_url',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
